DEVICE_ENV: REAL

# ================= SYSTEM BACKENDS =================
DISPLAY_MODE: "oled"        # "oled" hoặc "debug"
BUTTON_MODE:  "gpio"        # "gpio" (nút vật lý) hoặc "debug"
AUDIO_MODE:   "alsa"        # "alsa" cho USB soundcard / ALSA
POWER_MODE:   "ads1015"     # "ads1015" cho ADC I2C (ADS1015/ADS1115)

ARTIFACTS_DIR: "artifacts"

# ================= STT =================
STT_VI:
  MODEL_PATH: "artifacts/stt_vi/stt_vi_v3.onnx"
  PROCESSOR_DIR: "artifacts/stt_vi/processor"

STT_EN:
  MODEL_PATH: "artifacts/stt_en/stt_en_v1.onnx"
  PROCESSOR_DIR: "artifacts/stt_en/processor"

# ================= NMT =================
NMT:
  VI_EN:
    MODEL_DIR: "artifacts/nmt_vi_en"
  EN_VI:
    MODEL_DIR: "artifacts/nmt_en_vi"

# ================= TTS =================
TTS:
  EN:
    BACKEND: "piper"
    PIPER_EXE: "/home/tuhieu/translator-device/venv/bin/piper"
    VOICE: "artifacts/tts_en/en_US-ljspeech-high.onnx"
    MODEL_PATH: "artifacts/tts_en/en_US-ljspeech-high.onnx"

  VI:
    BACKEND: "piper"
    PIPER_EXE: "/home/tuhieu/translator-device/venv/bin/piper"
    VOICE: "artifacts/tts_vi/vi_VN-vais1000-medium.onnx"
    MODEL_PATH: "artifacts/tts_en/en_US-ljspeech-high.onnx"

# ================= AUDIO =================
AUDIO:
  SAMPLE_RATE: 48000
  STT_RATE: 16000
  CHANNELS: 1
  INPUT_DEVICE: 0
  OUTPUT_DEVICE: 0

# ================= BUTTON GPIO =================
BUTTONS:
  TALK_PIN: 17
  MODE_PIN: 27
  LONG_PRESS_SEC: 5.0

# ================= DISPLAY (OLED) =================
DISPLAY:
  TYPE: "ssd1306"
  WIDTH: 128
  HEIGHT: 64
  I2C_BUS: 1
  I2C_ADDRESS: 0x3C

# ================= POWER (ADS1015) =================
POWER:
  ADC: "ads1015"
  I2C_BUS: 1
  I2C_ADDRESS: 0x48
  CHANNEL: 0
  R1: 330000
  R2: 100000
  MIN_V: 3.2
  MAX_V: 4.2