# ==== Backend mode ====
DISPLAY_MODE: "debug"   # "debug" hoặc "oled"
BUTTON_MODE:  "debug"   # laptop: debug | pi: gpio
AUDIO_MODE:   "debug"   # tùy backend audio bạn dùng
POWER_MODE:   "debug"   # laptop: debug | pi: pi

ARTIFACTS_DIR: "artifacts"

# ===== STT (onnx CTC) =====
STT_VI:
  MODEL_PATH: "artifacts/stt_vi/stt_vi_v3.onnx"
  PROCESSOR_DIR: "artifacts/stt_vi/processor"

STT_EN:
  MODEL_PATH: "artifacts/stt_en/stt_en_v1.onnx"
  PROCESSOR_DIR: "artifacts/stt_en/processor"

# ===== NMT =====
NMT:
  VI_EN:
    MODEL_DIR: "artifacts/nmt_vi_en"
  EN_VI:
    MODEL_DIR: "artifacts/nmt_en_vi"
  EN_EN:
    MODEL_DIR: "artifacts/nmt_en_en"

# ===== TTS =====
TTS:
  EN:
    BACKEND: "piper"
    PIPER_EXE: "piper"     # Windows: "piper.exe" hoặc path đầy đủ
    VOICE: "artifacts/tts_en/en_US-ljspeech-high.onnx"

  VI:
    BACKEND: "piper"
    PIPER_EXE: "piper"     # Windows: "piper.exe" hoặc path đầy đủ
    VOICE: "artifacts/tts_vi/vi_VN-vais1000-medium.onnx"

# ===== Audio =====
AUDIO:
  SAMPLE_RATE: 16000
  CHANNELS: 1
  MAX_RECORD_SECONDS: 7

# ===== Buttons (Pi) =====
BUTTONS:
  TALK_PIN: 23
  MODE_PIN: 24
